"""Generate the StyleSense AI Colab notebook as a proper .ipynb file."""
import json
import os

cells = []

# --- Markdown: Title ---
cells.append({
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "# 🧠 StyleSense AI — Fashion Detection Backend\n",
        "\n",
        "This notebook runs the real fashion detection model and exposes an API.\n",
        "\n",
        "**Steps:**\n",
        "1. Set your ngrok token in the config cell below\n",
        "2. Runtime → Change runtime type → **GPU**\n",
        "3. **Run All** (Ctrl+F9)\n",
        "4. Copy the printed URL → paste into your local `.env` as `COLAB_API_URL`"
    ]
})

# --- Code: Install ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "!pip install -q transformers torch torchvision pillow fastapi uvicorn pyngrok python-multipart scikit-learn opencv-python-headless nest-asyncio"
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Config ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# ============================================\n",
        "# CONFIGURATION — Set your ngrok token here\n",
        "# Get a free token: https://dashboard.ngrok.com/signup\n",
        "# ============================================\n",
        "\n",
        'NGROK_AUTH_TOKEN = ""  # <-- PASTE YOUR TOKEN HERE\n',
        "\n",
        "CONFIDENCE_THRESHOLD = 0.4  # Lower = more detections, higher = stricter"
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Imports + Model Loading ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "import io\n",
        "import random\n",
        "import numpy as np\n",
        "import cv2\n",
        "import torch\n",
        "from PIL import Image\n",
        "from sklearn.cluster import KMeans\n",
        "from transformers import AutoImageProcessor, AutoModelForObjectDetection\n",
        "\n",
        'MODEL_NAME = "valentinafeve/yolos-fashionpedia"\n',
        "\n",
        'print("⏳ Loading fashion detection model... (first run may take ~2 min)")\n',
        "processor = AutoImageProcessor.from_pretrained(MODEL_NAME)\n",
        "model = AutoModelForObjectDetection.from_pretrained(MODEL_NAME)\n",
        "model.eval()\n",
        "\n",
        'device = torch.device("cuda" if torch.cuda.is_available() else "cpu")\n',
        "model = model.to(device)\n",
        'print(f"✅ Model loaded on {device}")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Categories + Colors ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "# Fashionpedia 27 clothing categories\n",
        "FASHIONPEDIA_CATEGORIES = {\n",
        '    0: {"name": "shirt", "display": "Shirt / Blouse", "icon": "👔", "group": "top"},\n',
        '    1: {"name": "top", "display": "Top / T-Shirt", "icon": "👕", "group": "top"},\n',
        '    2: {"name": "sweater", "display": "Sweater", "icon": "🧶", "group": "top"},\n',
        '    3: {"name": "cardigan", "display": "Cardigan", "icon": "🧥", "group": "top"},\n',
        '    4: {"name": "jacket", "display": "Jacket", "icon": "🧥", "group": "outerwear"},\n',
        '    5: {"name": "vest", "display": "Vest", "icon": "🦺", "group": "top"},\n',
        '    6: {"name": "pants", "display": "Pants", "icon": "👖", "group": "bottom"},\n',
        '    7: {"name": "shorts", "display": "Shorts", "icon": "🩳", "group": "bottom"},\n',
        '    8: {"name": "skirt", "display": "Skirt", "icon": "👗", "group": "bottom"},\n',
        '    9: {"name": "coat", "display": "Coat", "icon": "🧥", "group": "outerwear"},\n',
        '    10: {"name": "dress", "display": "Dress", "icon": "👗", "group": "full-body"},\n',
        '    11: {"name": "jumpsuit", "display": "Jumpsuit", "icon": "👗", "group": "full-body"},\n',
        '    12: {"name": "cape", "display": "Cape", "icon": "🧥", "group": "outerwear"},\n',
        '    13: {"name": "glasses", "display": "Glasses", "icon": "👓", "group": "accessory"},\n',
        '    14: {"name": "hat", "display": "Hat", "icon": "🎩", "group": "accessory"},\n',
        '    15: {"name": "headband", "display": "Headband / Hair Accessory", "icon": "💇", "group": "accessory"},\n',
        '    16: {"name": "tie", "display": "Tie", "icon": "👔", "group": "accessory"},\n',
        '    17: {"name": "glove", "display": "Gloves", "icon": "🧤", "group": "accessory"},\n',
        '    18: {"name": "watch", "display": "Watch", "icon": "⌚", "group": "accessory"},\n',
        '    19: {"name": "belt", "display": "Belt", "icon": "🪢", "group": "accessory"},\n',
        '    20: {"name": "leg_warmer", "display": "Leg Warmer", "icon": "🧦", "group": "bottom"},\n',
        '    21: {"name": "tights", "display": "Tights / Stockings", "icon": "🧦", "group": "bottom"},\n',
        '    22: {"name": "sock", "display": "Socks", "icon": "🧦", "group": "footwear"},\n',
        '    23: {"name": "shoe", "display": "Shoes", "icon": "👟", "group": "footwear"},\n',
        '    24: {"name": "bag", "display": "Bag / Wallet", "icon": "👜", "group": "accessory"},\n',
        '    25: {"name": "scarf", "display": "Scarf", "icon": "🧣", "group": "accessory"},\n',
        '    26: {"name": "umbrella", "display": "Umbrella", "icon": "☂️", "group": "accessory"},\n',
        "}\n",
        "\n",
        "# Named color mapping (RGB)\n",
        "COLOR_MAP = {\n",
        '    "black": (0, 0, 0), "white": (255, 255, 255), "navy": (0, 0, 128),\n',
        '    "blue": (0, 0, 255), "light blue": (135, 206, 235), "red": (255, 0, 0),\n',
        '    "dark red": (139, 0, 0), "green": (0, 128, 0), "dark green": (0, 100, 0),\n',
        '    "gray": (128, 128, 128), "light gray": (192, 192, 192), "dark gray": (64, 64, 64),\n',
        '    "beige": (245, 245, 220), "brown": (139, 90, 43), "tan": (210, 180, 140),\n',
        '    "pink": (255, 182, 193), "hot pink": (255, 105, 180), "purple": (128, 0, 128),\n',
        '    "lavender": (186, 147, 216), "orange": (255, 165, 0), "yellow": (255, 255, 0),\n',
        '    "olive": (128, 128, 0), "burgundy": (128, 0, 32), "teal": (0, 128, 128),\n',
        '    "cream": (255, 253, 208), "coral": (255, 127, 80), "maroon": (128, 0, 0),\n',
        '    "khaki": (195, 176, 145), "denim blue": (80, 102, 140),\n',
        "}\n",
        "\n",
        'print(f"✅ {len(FASHIONPEDIA_CATEGORIES)} clothing categories loaded")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Color extraction ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "def closest_color_name(rgb):\n",
        '    """Find the nearest named color for an RGB tuple."""\n',
        '    min_dist = float("inf")\n',
        '    name = "unknown"\n',
        "    for cname, crgb in COLOR_MAP.items():\n",
        "        dist = sum((a - b) ** 2 for a, b in zip(rgb, crgb))\n",
        "        if dist < min_dist:\n",
        "            min_dist = dist\n",
        "            name = cname\n",
        "    return name\n",
        "\n",
        "def rgb_to_hex(rgb):\n",
        '    return "#{:02x}{:02x}{:02x}".format(int(rgb[0]), int(rgb[1]), int(rgb[2]))\n',
        "\n",
        "def extract_region_color(image_np, bbox, n_colors=3):\n",
        '    """Extract dominant color from a bounding box region."""\n',
        "    h, w = image_np.shape[:2]\n",
        "    x1 = max(0, int(bbox[0]))\n",
        "    y1 = max(0, int(bbox[1]))\n",
        "    x2 = min(w, int(bbox[2]))\n",
        "    y2 = min(h, int(bbox[3]))\n",
        "    region = image_np[y1:y2, x1:x2]\n",
        "    if region.size == 0 or region.shape[0] < 5 or region.shape[1] < 5:\n",
        '        return "unknown", "#808080"\n',
        "    region_small = cv2.resize(region, (50, 50))\n",
        "    pixels = region_small.reshape(-1, 3).astype(float)\n",
        "    # Filter out skin tones\n",
        "    mask = ~((pixels[:, 0] > 140) & (pixels[:, 1] > 80) & (pixels[:, 1] < pixels[:, 0]) & (pixels[:, 2] < pixels[:, 1]))\n",
        "    filtered = pixels[mask]\n",
        "    if len(filtered) < 20:\n",
        "        filtered = pixels\n",
        "    k = min(n_colors, len(filtered))\n",
        "    if k < 1:\n",
        '        return "unknown", "#808080"\n',
        "    kmeans = KMeans(n_clusters=k, n_init=5, random_state=42)\n",
        "    kmeans.fit(filtered)\n",
        "    counts = np.bincount(kmeans.labels_)\n",
        "    dominant_idx = np.argmax(counts)\n",
        "    dominant_rgb = kmeans.cluster_centers_[dominant_idx]\n",
        "    return closest_color_name(dominant_rgb), rgb_to_hex(dominant_rgb)\n",
        "\n",
        "def extract_palette(image_np, items_bboxes, n_colors=5):\n",
        '    """Extract overall color palette from all clothing regions."""\n',
        "    all_pixels = []\n",
        "    for bbox in items_bboxes:\n",
        "        h, w = image_np.shape[:2]\n",
        "        x1, y1, x2, y2 = max(0, int(bbox[0])), max(0, int(bbox[1])), min(w, int(bbox[2])), min(h, int(bbox[3]))\n",
        "        region = image_np[y1:y2, x1:x2]\n",
        "        if region.size == 0:\n",
        "            continue\n",
        "        region_small = cv2.resize(region, (40, 40))\n",
        "        all_pixels.append(region_small.reshape(-1, 3))\n",
        "    if not all_pixels:\n",
        "        return []\n",
        "    combined = np.vstack(all_pixels).astype(float)\n",
        "    k = min(n_colors, len(combined))\n",
        "    if k < 1:\n",
        "        return []\n",
        "    kmeans = KMeans(n_clusters=k, n_init=5, random_state=42)\n",
        "    kmeans.fit(combined)\n",
        "    counts = np.bincount(kmeans.labels_)\n",
        "    total = len(kmeans.labels_)\n",
        "    dominant_idx = int(np.argmax(counts))\n",
        "    palette = []\n",
        "    for i in range(k):\n",
        "        rgb = kmeans.cluster_centers_[i]\n",
        "        palette.append({\n",
        '            "name": closest_color_name(rgb),\n',
        '            "hex": rgb_to_hex(rgb),\n',
        '            "percentage": round(float(counts[i] / total) * 100, 1),\n',
        '            "is_dominant": i == dominant_idx,\n',
        "        })\n",
        '    palette.sort(key=lambda x: x["percentage"], reverse=True)\n',
        "    return palette\n",
        "\n",
        'print("✅ Color extraction ready")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Detection ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "def compute_iou(box1, box2):\n",
        '    """Compute IoU between two normalized boxes [x1,y1,x2,y2]."""\n',
        "    x1 = max(box1[0], box2[0])\n",
        "    y1 = max(box1[1], box2[1])\n",
        "    x2 = min(box1[2], box2[2])\n",
        "    y2 = min(box1[3], box2[3])\n",
        "    inter = max(0, x2 - x1) * max(0, y2 - y1)\n",
        "    area1 = (box1[2] - box1[0]) * (box1[3] - box1[1])\n",
        "    area2 = (box2[2] - box2[0]) * (box2[3] - box2[1])\n",
        "    union = area1 + area2 - inter\n",
        "    return inter / union if union > 0 else 0\n",
        "\n",
        "def detect_clothing(image_pil):\n",
        '    """Detect clothing items in a PIL image."""\n',
        '    inputs = processor(images=image_pil, return_tensors="pt")\n',
        "    inputs = {k: v.to(device) for k, v in inputs.items()}\n",
        "    with torch.no_grad():\n",
        "        outputs = model(**inputs)\n",
        "    target_sizes = torch.tensor([image_pil.size[::-1]], device=device)\n",
        "    results = processor.post_process_object_detection(outputs, target_sizes=target_sizes, threshold=CONFIDENCE_THRESHOLD)\n",
        "    if not results:\n",
        "        return []\n",
        '    result = results[0]\n',
        '    boxes = result["boxes"].cpu().numpy()\n',
        '    scores = result["scores"].cpu().numpy()\n',
        '    labels = result["labels"].cpu().numpy()\n',
        "    image_np = np.array(image_pil)\n",
        "    h, w = image_np.shape[:2]\n",
        "    detections = []\n",
        "    for box, score, label in zip(boxes, scores, labels):\n",
        "        label_int = int(label)\n",
        "        if label_int not in FASHIONPEDIA_CATEGORIES:\n",
        "            continue\n",
        "        cat = FASHIONPEDIA_CATEGORIES[label_int]\n",
        "        x1, y1, x2, y2 = box\n",
        "        color_name, color_hex = extract_region_color(image_np, [x1, y1, x2, y2])\n",
        "        detections.append({\n",
        '            "category": cat["name"],\n',
        '            "display_name": cat["display"],\n',
        '            "color": color_name,\n',
        '            "color_hex": color_hex,\n',
        '            "confidence": round(float(score), 3),\n',
        '            "bbox": [\n',
        "                round(float(x1) / w, 4),\n",
        "                round(float(y1) / h, 4),\n",
        "                round(float(x2) / w, 4),\n",
        "                round(float(y2) / h, 4),\n",
        "            ],\n",
        '            "icon": cat["icon"],\n',
        '            "group": cat["group"],\n',
        "        })\n",
        '    detections.sort(key=lambda x: x["confidence"], reverse=True)\n',
        "    # Deduplicate overlapping same-category detections\n",
        "    final = []\n",
        "    for det in detections:\n",
        "        is_dup = False\n",
        "        for existing in final:\n",
        '            if existing["category"] == det["category"]:\n',
        '                if compute_iou(det["bbox"], existing["bbox"]) > 0.5:\n',
        "                    is_dup = True\n",
        "                    break\n",
        "        if not is_dup:\n",
        "            final.append(det)\n",
        "    return final\n",
        "\n",
        'print("✅ Clothing detection ready")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Style classification ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "STYLE_RULES = {\n",
        '    "formal": {\n',
        '        "requires_any": ["shirt", "tie", "coat", "dress"],\n',
        '        "boost_items": ["belt", "watch", "glasses"],\n',
        '        "penalize": ["shorts", "sock", "hat"],\n',
        "    },\n",
        '    "casual": {\n',
        '        "requires_any": ["top", "pants", "shoe", "shorts"],\n',
        '        "boost_items": ["bag", "scarf"],\n',
        '        "penalize": ["tie", "coat"],\n',
        "    },\n",
        '    "sporty": {\n',
        '        "requires_any": ["shorts", "top", "shoe", "sock"],\n',
        '        "boost_items": ["hat", "watch"],\n',
        '        "penalize": ["tie", "dress", "coat", "shirt"],\n',
        "    },\n",
        '    "streetwear": {\n',
        '        "requires_any": ["jacket", "pants", "shoe", "hat"],\n',
        '        "boost_items": ["bag", "scarf", "glasses"],\n',
        '        "penalize": ["tie", "dress"],\n',
        "    },\n",
        '    "smart casual": {\n',
        '        "requires_any": ["shirt", "pants", "shoe", "sweater", "cardigan"],\n',
        '        "boost_items": ["belt", "watch", "bag"],\n',
        '        "penalize": ["shorts", "sock"],\n',
        "    },\n",
        '    "bohemian": {\n',
        '        "requires_any": ["dress", "skirt", "scarf"],\n',
        '        "boost_items": ["hat", "bag", "headband"],\n',
        '        "penalize": ["tie", "coat"],\n',
        "    },\n",
        "}\n",
        "\n",
        "def classify_style(items):\n",
        '    """Rule-based style classification from detected items."""\n',
        "    if not items:\n",
        '        return {"label": "unknown", "secondary_label": None, "confidence": 0.0,\n',
        '                "insight": "We couldn\'t determine a style direction from this image."}\n',
        '    item_names = {item["category"] for item in items}\n',
        '    colors = [item["color"] for item in items]\n',
        "    scores = {}\n",
        "    for style, rules in STYLE_RULES.items():\n",
        "        score = 0.0\n",
        '        matches = item_names & set(rules["requires_any"])\n',
        "        score += len(matches) * 0.3\n",
        '        boosts = item_names & set(rules["boost_items"])\n',
        "        score += len(boosts) * 0.1\n",
        '        penalties = item_names & set(rules["penalize"])\n',
        "        score -= len(penalties) * 0.15\n",
        "        scores[style] = max(0.0, score)\n",
        "    if not any(scores.values()):\n",
        '        scores["casual"] = 0.3\n',
        "    sorted_styles = sorted(scores.items(), key=lambda x: x[1], reverse=True)\n",
        "    best = sorted_styles[0]\n",
        "    second = sorted_styles[1] if len(sorted_styles) > 1 else None\n",
        '    item_list = [item["display_name"] for item in items[:4]]\n',
        "    color_list = list(dict.fromkeys(colors))[:3]\n",
        "    if len(item_list) == 1:\n",
        "        items_text = item_list[0]\n",
        "    elif len(item_list) == 2:\n",
        '        items_text = f"{item_list[0]} and {item_list[1]}"\n',
        "    else:\n",
        '        items_text = ", ".join(item_list[:-1]) + f", and {item_list[-1]}"\n',
        '    color_text = " and ".join(color_list[:2]) if color_list else "mixed"\n',
        "    style_label = best[0]\n",
        "    insight_templates = [\n",
        '        f"Your outfit features {items_text} with a {color_text} color direction — reading as {style_label}.",\n',
        '        f"A {style_label} look built around {items_text} in {color_text} tones.",\n',
        '        f"We see {items_text} creating a {style_label} silhouette with {color_text} as the dominant palette.",\n',
        "    ]\n",
        "    return {\n",
        '        "label": best[0],\n',
        '        "secondary_label": second[0] if second and second[1] > 0.15 else None,\n',
        '        "confidence": round(min(best[1] / 0.9, 1.0), 2),\n',
        '        "insight": random.choice(insight_templates),\n',
        "    }\n",
        "\n",
        'print("✅ Style classification ready")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Full pipeline ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "def analyze_image(image_pil):\n",
        '    """Run the complete analysis pipeline on a PIL image."""\n',
        "    # 1. Detect clothing\n",
        "    items = detect_clothing(image_pil)\n",
        "    # 2. Extract palette from clothing regions\n",
        "    image_np = np.array(image_pil)\n",
        "    h, w = image_np.shape[:2]\n",
        "    bboxes_abs = []\n",
        "    for item in items:\n",
        '        b = item["bbox"]\n',
        "        bboxes_abs.append([b[0]*w, b[1]*h, b[2]*w, b[3]*h])\n",
        "    palette = extract_palette(image_np, bboxes_abs, n_colors=5) if bboxes_abs else []\n",
        "    # 3. Classify style\n",
        "    style = classify_style(items)\n",
        "    # 4. Clean items (remove group field)\n",
        '    clean_items = [{k: v for k, v in item.items() if k != "group"} for item in items]\n',
        "    return {\n",
        '        "success": True,\n',
        '        "data": {\n',
        '            "items": clean_items,\n',
        '            "palette": palette,\n',
        '            "style": style,\n',
        '            "item_count": len(clean_items),\n',
        '            "is_demo": False,\n',
        "        },\n",
        '        "error": None,\n',
        '        "message": f"Detected {len(clean_items)} clothing item(s)",\n',
        "    }\n",
        "\n",
        "# Self-test\n",
        'test = analyze_image(Image.new("RGB", (200, 200), (100, 100, 200)))\n',
        'print(f"✅ Pipeline self-test OK — detected {test[\'data\'][\'item_count\']} items in blank test image")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: FastAPI ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "from fastapi import FastAPI, UploadFile, File\n",
        "from fastapi.middleware.cors import CORSMiddleware\n",
        "from fastapi.responses import JSONResponse\n",
        "\n",
        'app = FastAPI(title="StyleSense AI - Colab Backend")\n',
        "\n",
        "app.add_middleware(\n",
        "    CORSMiddleware,\n",
        '    allow_origins=["*"],\n',
        "    allow_credentials=True,\n",
        '    allow_methods=["*"],\n',
        '    allow_headers=["*"],\n',
        ")\n",
        "\n",
        '@app.get("/api/health")\n',
        "def health():\n",
        '    return {"status": "ok", "demo_mode": False, "device": str(device), "model": MODEL_NAME}\n',
        "\n",
        '@app.get("/api/config")\n',
        "def config():\n",
        '    return {"demo_mode": False, "max_image_size": 10 * 1024 * 1024, "allowed_extensions": ["jpg", "jpeg", "png", "webp"]}\n',
        "\n",
        '@app.post("/api/analyze")\n',
        "async def analyze(file: UploadFile = File(...)):\n",
        "    try:\n",
        "        contents = await file.read()\n",
        "        if len(contents) > 10 * 1024 * 1024:\n",
        "            return JSONResponse(status_code=400, content={\n",
        '                "success": False, "data": None,\n',
        '                "error": "Image too large. Please upload under 10MB.", "message": None\n',
        "            })\n",
        '        image = Image.open(io.BytesIO(contents)).convert("RGB")\n',
        "        max_dim = 1024\n",
        "        if max(image.size) > max_dim:\n",
        "            ratio = max_dim / max(image.size)\n",
        "            new_size = (int(image.size[0] * ratio), int(image.size[1] * ratio))\n",
        "            image = image.resize(new_size, Image.LANCZOS)\n",
        "        result = analyze_image(image)\n",
        "        return JSONResponse(content=result)\n",
        "    except Exception as e:\n",
        "        import traceback\n",
        "        traceback.print_exc()\n",
        "        return JSONResponse(status_code=500, content={\n",
        '            "success": False, "data": None,\n',
        '            "error": f"Analysis failed: {str(e)}", "message": None\n',
        "        })\n",
        "\n",
        'print("✅ FastAPI app created")'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Code: Start server ---
cells.append({
    "cell_type": "code",
    "metadata": {},
    "source": [
        "import nest_asyncio\n",
        "nest_asyncio.apply()\n",
        "\n",
        "if NGROK_AUTH_TOKEN:\n",
        "    from pyngrok import ngrok, conf\n",
        "    conf.get_default().auth_token = NGROK_AUTH_TOKEN\n",
        "    tunnel = ngrok.connect(8000)\n",
        "    public_url = tunnel.public_url\n",
        "else:\n",
        "    try:\n",
        "        from pyngrok import ngrok\n",
        "        tunnel = ngrok.connect(8000)\n",
        "        public_url = tunnel.public_url\n",
        "    except Exception:\n",
        '        public_url = "http://localhost:8000"\n',
        '        print("⚠️  ngrok not configured. Set NGROK_AUTH_TOKEN in the config cell above.")\n',
        '        print("   Get a free token: https://dashboard.ngrok.com/signup")\n',
        "\n",
        'print()\n',
        'print("=" * 60)\n',
        'print("🚀 StyleSense AI Backend is LIVE!")\n',
        'print("=" * 60)\n',
        'print(f"\\n   📡 Public URL: {public_url}")\n',
        'print(f"\\n   Paste this in your backend .env:")\n',
        'print(f"   COLAB_API_URL={public_url}")\n',
        'print(f"\\n   Test it: {public_url}/api/health")\n',
        'print("=" * 60)\n',
        "\n",
        "import uvicorn\n",
        'uvicorn.run(app, host="0.0.0.0", port=8000)'
    ],
    "execution_count": None,
    "outputs": []
})

# --- Build the notebook ---
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "name": "StyleSense_AI_Fashion_Detection.ipynb",
            "provenance": [],
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        },
        "accelerator": "GPU",
        "gpuClass": "standard"
    },
    "cells": cells
}

output_path = os.path.join(os.path.dirname(__file__), "StyleSense_AI_Fashion_Detection.ipynb")
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2, ensure_ascii=False)

print(f"OK - Notebook saved to: {output_path}")
